// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var MoviePanel;

  this.movieApp = angular.module('movieApp', []);

  MoviePanel = (function() {
    function MoviePanel($scope1, $http1) {
      this.$scope = $scope1;
      this.$http = $http1;
      $scope.searchInput = "";
      $scope.dropDownInvisible = true;
      $scope.movieInfoInvisible = true;
      $scope.search = function() {
        var results, searchTerm;
        if ($scope.searchInput) {
          $scope.movieList = [];
          $scope.dropDownInvisible = true;
          searchTerm = $scope.searchInput;
          $http({
            url: "http://www.omdbapi.com/",
            method: "get",
            params: {
              s: searchTerm
            }
          }).success(function(data, status, headers, config) {
            console.log("data: " + data + "status: " + status + "headers:" + headers + "config: " + config);
            return results(data);
          }).error(function(data, status, headers, config) {
            return $scope.status = status;
          });
          return results = function(data) {
            var i, len, movie, ref, results1;
            $scope.loadingGif = true;
            if (data.Response !== 'False') {
              $scope.movieList = [];
              $scope.dropDownInvisible = false;
              ref = data["Search"];
              results1 = [];
              for (i = 0, len = ref.length; i < len; i++) {
                movie = ref[i];
                results1.push($scope.movieList.push(movie));
              }
              return results1;
            }
          };
        }
      };
      $scope.searchPick = function($event, movie) {
        var imdbInfo;
        $scope.movieInfo = {};
        $scope.dropDownInvisible = true;
        $scope.movieInfoInvisible = false;
        $http({
          url: "http://www.omdbapi.com/",
          method: "get",
          params: {
            i: movie.imdbID
          }
        }).success(function(data, status, headers, config) {
          console.log("data: " + data + "status: " + status + "headers:" + headers + "config: " + config + "imdbID: " + movie.imdbID);
          return imdbInfo(data);
        }).error(function(data, status, headers, config) {
          return $scope.status = status;
        });
        return imdbInfo = function(data) {
          var info, key, results1;
          results1 = [];
          for (key in data) {
            info = data[key];
            results1.push($scope.movieInfo[key] = info);
          }
          return results1;
        };
      };
    }

    return MoviePanel;

  })();

  MoviePanel.$inject = ["$scope", "$http"];

  movieApp.controller("MoviePanel", MoviePanel);

}).call(this);
